### ISSUE TITLE
World Boss Event - Incorrect Infomation

### ISSUE THREAD

**Issue by merson316** [nminchow/black-book#2]
Hello!

We've noticed that the world boss event posts are a bit flakey with misinformation posted every now and then or posted multiple times in short succession. Is it possible for the bot to only post something once it has been marked as confirmed on diablo4.life? Seems like people are spamming false reports there now and some are slipping through the cracks.

**Comment by nminchow** [comment]
I overhauled our whole data sourcing scheme in https://github.com/nminchow/black-book/commit/aa01cb538d89ad63bf782969e04fa4f33955ccb0, which was merged yesterday. Have you sen any issues since then?

**Comment by merson316** [comment]
I have not! 

Thanks very much for this and the other improvements as well. It has been a very useful bot so far.
