### ISSUE TITLE
Map Image

### ISSUE THREAD

**Issue by robotrono** [nminchow/black-book#3]
Is it possible to add the image of the event map in the message for Helltides, world boss and legion?

**Comment by nminchow** [comment]
yup! keep an eye on: https://github.com/nminchow/black-book/tree/images-in-notifications

**Comment by robotrono** [comment]
Thanks so much, now I'm trying to configure the Bot, but in the settings you mention that I need a Github token, is it necessary?
If so, which scopes do I enable for the github token creation app? Sorry is my firs time to make a bot.

**Comment by nminchow** [comment]
> Thanks so much, now I'm trying to configure the Bot, but in the settings you mention that I need a Github token, is it necessary? If so, which scopes do I enable for the github token creation app? Sorry is my firs time to make a bot.

These questions are probably better suited to the discord server! (or a separate issue)

For posterity, the token is necessary. It is used to pull the database files for skills and affixes.
